engines/Spaces

- ruby/nodule/lua/lua.rb
- ruby/nodule/lua/scripts/installation.rb
- ruby/nodule/npm/npm.rb
- ruby/nodule/npm/scripts/installation.rb
- ruby/nodule/pear/pear.rb
- ruby/nodule/pear/scripts/installation.rb
- ruby/nodule/pecl/pecl.rb
- ruby/nodule/pecl/scripts/installation.rb
- ruby/nodule/python/python.rb
- ruby/nodule/python/scripts/installation.rb
- ruby/nodule/r/r.rb
- ruby/nodule/r/scripts/installation.rb
- ruby/spaces/script.rb
In addition I have added a final method to Scripts Class
This is support clean up commands post install of all modules
This was required for the pear installation script
> Complet Nodules install scripts

- ruby/bindings/binding.rb
- ruby/bindings/relationship.rb
- ruby/texts/infix.rb
for example:
```"password": "random(10)"```
works
> refine anchoring, binding & infixing to allow argument passing on method calls

- ruby/images/subject.rb
- ruby/installations/installation.rb
- ruby/sudos/scripts/create_sudoers.rb
- ruby/sudos/steps/run_scripts.rb
- ruby/sudos/sudo.rb
- ruby/sudos/sudos.rb
missing run create_sudo  in Dockerfile
> create sudo script

- README.md
- ruby/domains/space.rb
- ruby/installations/installation.rb
- ruby/lib/ostruct.rb
- ruby/projects/space.rb
- ruby/spaces/descriptor.rb
- ruby/spaces/space.rb
- ruby/users/space.rb
- ruby/x/blank.rb
- ruby/x/filesystem.rb
- ruby/x/hello_world.rb
- ruby/x/mysqld.rb
- ruby/x/phpmyadmin.rb
- ruby/x/publify.rb
- ruby/x/save.rb
- ruby/x/test_container.rb
- web/server/api.rb
plus major rethink of descriptor implementation
> FIX BUG: installation descriptor not saving properly

- ruby/bindings/binding.rb
- ruby/blueprints/space.rb
- ruby/docker/files/file.rb
- ruby/recovery/i18n/en.yaml
- ruby/releases/division.rb
- ruby/spaces/model.rb
- ruby/spaces/thing.rb
- ruby/x/mysql.rb
- ruby/x/mysqld.rb
also FIX: calling #warn in class methods calls standard method and crashes
> handle mal-formed blueprint subdivisions

- src/engines/blueprinting/space.rb
- src/engines/packing/pack.rb
- src/engines/packing/space.rb
- src/engines/requires.rb
- src/requires.rb
- src/spaces/git/space.rb
- src/spaces/interpolating/file_text.rb
- src/spaces/models/descriptor.rb
- src/spaces/models/recovery/trace.rb
- src/spaces/models/space.rb
Replace Dir, File, FileUtils methods with equivalents from Pathname Class.
> Pathname instead of Dir, File, FileUtils

- src/engines/packing/pack.rb
> define helper methods for finding pre-built packing scripts

- src/engines/emitting/divisions/bindings/binding.rb
- src/engines/emitting/divisions/bindings/bindings.rb
- src/engines/emitting/divisions/configuration.rb
- src/engines/emitting/emissions/emission.rb
- src/engines/emitting/emissions/resolvable.rb
- src/engines/emitting/emissions/transformable.rb
- src/spaces/interpolating/text.rb
- src/spaces/lib/array.rb
> helper methods for testing the completeness of emissions and their components

- src/engines/arenas/space.rb
> Fix arena space bugs

- src/engines/emitting/associations/domains/domain.rb
- src/engines/emitting/associations/tenants/space.rb
- src/engines/emitting/associations/tenants/tenant.rb
- src/engines/emitting/emissions/association.rb
- src/engines/resolving/resolution.rb
> provide behaviour for crudding domains & tenants

- src/engines/emitting/emissions/association.rb
> FIX BUG: division#prototype passes wrong params to associations#initialize

- src/providers/dns/power_dns.rb
> FIX BUG: syntax error in PowerDns#arena_stanzas

- src/engines/emitting/emissions/association.rb
- src/spaces/interpolating/file_text.rb
- src/spaces/interpolating/one_time_script.rb
- src/spaces/models/descriptor.rb
These are the requires I had to add to get spaces up
> fix requires

- src/spaces/lib/array.rb
> FIX BUG: Array#to_struct incorrectly converting simple values to hash

- src/engines/blueprinting/space.rb
Allias :save_json with :save in Blueprinting space.
> Save blueprints as JSON.

- src/engines/blueprinting/divisions/images/image.rb
- src/providers/virtualisation/docker/image.rb
- src/providers/virtualisation/lxd/image.rb
> default_name method is provider dependant

- src/engines/blueprinting/divisions/bindings/binding.rb
- src/engines/blueprinting/divisions/other_packages/other_package.rb
- src/engines/emissions/transformable.rb
- src/engines/packing/divisions/division.rb
turns out to be useful for UI’s
> ensure descriptors in resolutions hold an explicit identifier

- src/engines/blueprinting/divisions/about.rb
- src/engines/emissions/composition.rb
> implement About division

- src/requires.rb
> FIX: merge conflict notation remains in file

- src/engines/blueprinting/blueprint.rb
- src/engines/emissions/emission.rb
> FIX BUG: crashes because bindings no longer have #descriptor

- src/engines/transforming/divisions/division.rb
> FIX REGRESSION: can’t find divisions’ scripts

- src/engines/arenas/providing.rb
- src/engines/blueprinting/divisions/provider.rb
- src/engines/blueprinting/divisions/volumes/volume.rb
- src/engines/blueprinting/divisions/volumes/volumes.rb
- src/engines/blueprinting/space.rb
- src/engines/packing/divisions/scripts.rb
- src/engines/packing/space.rb
- src/engines/publishing/space.rb
- src/engines/resolving/resolution.rb
- src/engines/transforming/divisions/association.rb
- src/engines/transforming/divisions/bindings/binding.rb
- src/engines/transforming/divisions/bindings/bindings.rb
- src/engines/transforming/divisions/dividing.rb
- src/engines/transforming/divisions/divisible.rb
- src/engines/transforming/divisions/division.rb
- src/engines/transforming/divisions/subclass_divisible.rb
- src/engines/transforming/divisions/subdivision.rb
- src/engines/transforming/divisions/targeting_subdivision.rb
- src/engines/transforming/emissions/emission.rb
- src/engines/transforming/emissions/localizing.rb
- src/providers/dns/power_dns.rb
- src/providers/virtualisation/lxd/container.rb
- src/providers/virtualisation/lxd/lxd.rb
- src/spaces/models/recovery/i18n/en.yaml
- src/x/scripts.rb
everything under the scope of an Arena delegates knowledge of runtime type (e.g "lxd") to the arena
> make Arenas be the hubs for knowing what container software they use

- lib/spaces/engines/resolving/packing.rb
- lib/spaces/engines/resolving/space.rb
- lib/spaces/engines/transforming/divisions/bindings/binding.rb
- lib/spaces/engines/transforming/divisions/divisible.rb
- lib/spaces/engines/transforming/divisions/division.rb
- lib/spaces/spaces/models/space.rb
> Disallow packing of resolutions that are not sensibly packable

- lib/spaces/engines/transforming/divisions/bindings/bindings.rb
- lib/spaces/engines/transforming/divisions/divisible.rb
- lib/spaces/engines/transforming/divisions/targeting_subdivision.rb
- lib/spaces/engines/transforming/emissions/targeting.rb
such as when ANY turtle has an embed … it ends up in the top turtle
> FIX BUG: irrelevent embeds are leaking into resolutions

- lib/spaces/spaces/lib/string.rb
- lib/spaces/spaces/models/paths.rb
- lib/spaces/spaces/models/reading.rb
- lib/spaces/spaces/models/space.rb
- lib/spaces/spaces/models/writing.rb
descriptors and other models are still acceptable
> Allow #empty? and others to accept an input string

- lib/spaces/spaces/lib/hash.rb
> FIX: #to_json should always have *args

- lib/spaces/engines/transforming/emissions/topology.rb
> FIX REGRESSION: missing topology methods

- lib/spaces/engines/resolving/packing.rb
- lib/spaces/engines/resolving/provisioning.rb
- lib/spaces/engines/transforming/emissions/resolving.rb
> cache arena & blueprint identifiers in arena emissions

- lib/spaces/engines/blueprinting/space.rb
- lib/spaces/engines/publishing/space.rb
- lib/spaces/engines/resolving/space.rb
- lib/spaces/engines/transforming/emissions/content.rb
- x/scripts.rb
also some refactoring of copying files with a view of later abstracting very similar implementations
> copy valid root files when synchronizing between publications and blueprints

- lib/spaces.rb
- lib/spaces/commands/requires.rb
> FIX BUG: uninitialized constant Arenas::Commands

- lib/spaces/commands/blueprinting/resolving.rb
- lib/spaces/commands/bootstrapping/initializing.rb
- lib/spaces/commands/provisioning/artifacts.rb
- lib/spaces/engines/blueprinting/space.rb
- lib/spaces/engines/transforming/emissions/emission.rb
- lib/spaces/spaces/commands/existing.rb
- lib/spaces/spaces/commands/modelling.rb
- lib/spaces/spaces/models/reading.rb
- lib/spaces/spaces/models/space.rb
- x/scripts.rb
also, allow space reading to use identifiables as input
> fix various command issues

- lib/spaces/spaces/git/respository.rb
> FIX BUGS: raising RepositoryFail from GitExecuteError crashes

- lib/spaces/engines/arenas/composition.rb
- lib/spaces/engines/resolving/resolution.rb
- lib/spaces/engines/transforming/emissions/hashing.rb
> allow an arena to have an About division

- Gemfile.lock
- lib/spaces/commands/packing/executing.rb
- lib/spaces/engines/arenas/space.rb
- lib/spaces/engines/arenas/terraforming.rb
- lib/spaces/engines/packing/pack.rb
- lib/spaces/engines/packing/packing.rb
- lib/spaces/engines/packing/space.rb
- lib/spaces/spaces/commands/executing.rb
- lib/spaces/spaces/commands/validating.rb
- spaces.gemspec
- x/scripts.rb
> reinstate Packer and Terraform execution interfaces

- lib/spaces/commands/arenas/binding.rb
- lib/spaces/commands/arenas/provider_provisioning.rb
- lib/spaces/commands/arenas/runtime_booting.rb
- lib/spaces/engines/arenas/arena.rb
- lib/spaces/engines/arenas/providing.rb
- lib/spaces/engines/arenas/space.rb
- lib/spaces/engines/blueprinting/divisions/provider.rb
- lib/spaces/engines/provisioning/provisions.rb
- lib/spaces/engines/provisioning/space.rb
- lib/spaces/engines/resolving/provisioning.rb
- lib/spaces/engines/transforming/divisions/bindings/binding.rb
- lib/spaces/providers/dns/power_dns.rb
- lib/spaces/providers/virtualisation/docker/docker.rb
- lib/spaces/providers/virtualisation/lxd/lxd.rb
- lib/spaces/spaces/commands/running.rb
- x/scripts.rb
> allow phased provisioning of providers

- lib/spaces/engines/blueprinting/divisions/ports/port.rb
- lib/spaces/engines/blueprinting/divisions/ports/ports.rb
- lib/spaces/engines/transforming/emissions/composition.rb
> identify Ports division

- lib/spaces/providers/virtualisation/lxd/lxd.rb
> FIX BUG and REFACTOR: #remote_Stanze returns nil when arena configuration declares no port value

- lib/spaces/commands/arenas/more_organizations.rb
- lib/spaces/commands/arenas/resolutions.rb
- lib/spaces/engines/arenas/arena.rb
- lib/spaces/engines/blueprinting/blueprint.rb
- lib/spaces/engines/blueprinting/space.rb
- lib/spaces/engines/transforming/emissions/binding.rb
- lib/spaces/spaces/commands/querying.rb
- x/scripts.rb
> implement commands for returning an arena’s “installed” resolutions

- lib/spaces/engines/blueprinting/divisions/ports/port.rb
- lib/spaces/engines/blueprinting/divisions/ports/ports.rb
- lib/spaces/engines/provisioning/provisions.rb
- lib/spaces/providers/virtualisation/lxd/container.rb
- lib/spaces/providers/virtualisation/lxd/lxd.rb
> build ports stanza into lxd_container resource

- Gemfile.lock
- spaces.gemspec
> addressable gem now version 2.8

- lib/spaces/engines/blueprinting/arenas.rb
- lib/spaces/engines/blueprinting/blueprint.rb
- lib/spaces/engines/transforming/emissions/topology.rb
> develop topology concern, inlcuding blueprints utilized in arenas

- lib/spaces/engines/transforming/divisions/targeting_subdivision.rb
> FIX BUG: published bindings without well-formed target causes SystemStackError

- lib/spaces/engines/blueprinting/space.rb
- lib/spaces/spaces/models/deleting.rb
- lib/spaces/spaces/models/saving.rb
- lib/spaces/spaces/models/space.rb
- x/scripts_base_image.rb
- x/scripts_docker.rb
> making deleting a blueprint cascade to deleting its publication

- lib/spaces/engines/arenas/installing.rb
- lib/spaces/engines/arenas/packing.rb
- lib/spaces/engines/arenas/provisioning.rb
- lib/spaces/engines/arenas/resolving.rb
- lib/spaces/engines/arenas/settling.rb
- lib/spaces/engines/arenas/space.rb
- lib/spaces/engines/arenas/state.rb
- lib/spaces/engines/publishing/space.rb
- lib/spaces/engines/transforming/divisions/targeting_subdivision.rb
- lib/spaces/spaces/lib/pathname.rb
- lib/spaces/spaces/models/model.rb
- lib/spaces/spaces/models/reading.rb
- lib/spaces/spaces/models/space.rb
> in arena state, test for freshness of various emissions

- lib/spaces/spaces/git/exporting.rb
- lib/spaces/spaces/git/importing.rb
- lib/spaces/spaces/git/respository.rb
- lib/spaces/spaces/git/space.rb
- lib/spaces/spaces/git/ssh.rb
> incorporate SSH into git space

- lib/spaces/engines/arenas/space.rb
- lib/spaces/engines/blueprinting/space.rb
- lib/spaces/engines/installing/space.rb
- lib/spaces/engines/provisioning/space.rb
- lib/spaces/engines/resolving/space.rb
- lib/spaces/spaces/git/exporting.rb
- lib/spaces/spaces/git/respository.rb
- x/scripts_docker.rb
> define cascading deletes

- lib/spaces/engines/publishing/space.rb
> FIX BUG: #by_import ignores force parameter

- lib/spaces/spaces/models/model.rb
- lib/spaces/spaces/models/space.rb
- lib/spaces/spaces/models/universe.rb
- x/universe.rb
> FIX BUG: undefined method `universe' for Spaces::Commands

- Gemfile
- Gemfile.lock
- lib/spaces/commands/arenas/building.rb
- lib/spaces/commands/packing/building.rb
- lib/spaces/controllers/arenas/controller.rb
- lib/spaces/controllers/packing/controller.rb
- lib/spaces/framework/lib/array.rb
- lib/spaces/framework/lib/hash.rb
- lib/spaces/framework/lib/ostruct.rb
- lib/spaces/framework/lib/string.rb
- lib/spaces/framework/lib/symbol.rb
- lib/spaces/models/emissions/arenas/arena.rb
- lib/spaces/models/emissions/arenas/interfacing.rb
- lib/spaces/models/emissions/arenas/phases/packing.rb
- lib/spaces/models/emissions/packing/pack.rb
- lib/spaces/models/emissions/packing/space.rb
- lib/spaces/models/emissions/provisioning/space.rb
- lib/spaces/models/transforming/artifacts/content.rb
- lib/spaces/providers/docker/interface.rb
- lib/spaces/providers/docker_compose/artifacts/build_stanza.rb
- lib/spaces/providers/docker_compose/artifacts/container_stanza.rb
- lib/spaces/providers/docker_compose/artifacts/containers_stanza.rb
- lib/spaces/providers/docker_compose/artifacts/deploy_stanza.rb
- lib/spaces/providers/docker_compose/interface.rb
- x/scripts_base_image.rb
- x/scripts_docker.rb
> BREAKING: very rough integration of docker-compose gem

- lib/spaces/providers/docker/interfaces/packing_interface.rb
> Rescue JSON errors when parsing Docker build output

- lib/spaces/models/divisions/volumes/volume.rb
- lib/spaces/providers/docker_compose/artifacts/volumes_stanza.rb
- x/scripts_docker.rb
- x/scripts_docker_database.rb
refine test scripts to use add, change, remove milestones
> change default volume type from bind -> mount 

- lib/spaces/commands/arenas/provisioning.rb
> FIX REGRESSION: arenas provision command not saving provisions yaml

- lib/spaces/framework/spaces/delegated_space.rb
- lib/spaces/models/transforming/emissions/interface_space.rb
> FIX BUG: InterfaceSpace#summaries returns full objects instead of a struct

- lib/spaces/providers/terraform/providers/aws/artifacts/security_group_stanza.rb
> clean up security group stanza configuration names

- lib/spaces/models/emissions/commissioning/commission.rb
- lib/spaces/models/emissions/commissioning/consumer.rb
> FIX REGRESSION: stack overflow on resolving ^^consumer.ip_address^^

- lib/spaces/framework/asserting/asserting.rb
- lib/spaces/framework/asserting/errors.rb
- lib/spaces/framework/spaces/deleting.rb
- lib/spaces/framework/streaming/space.rb
- lib/spaces/framework/streaming/space/stream/filing.rb
- lib/spaces/framework/streaming/space/stream/outputting.rb
- lib/spaces/models/divisions/ports/port.rb
- lib/spaces/models/emissions/arenas/associations/role_providers/role_providers.rb
- lib/spaces/models/emissions/arenas/providing.rb
- lib/spaces/models/transforming/providers/provider.rb
- lib/spaces/models/transforming/providers/space.rb
- lib/spaces/providers/docker_compose/artifacts/ports_stanza.rb
- lib/spaces/providers/terraform/adapters/orchestration.rb
- lib/spaces/providers/terraform/providers/aws/artifacts/container_registry_stanza.rb
- lib/spaces/providers/terraform/providers/aws/artifacts/container_service_stanza.rb
- lib/spaces/providers/terraform/providers/aws/artifacts/container_task_definition_stanza.rb
- lib/spaces/providers/terraform/providers/aws/artifacts/support.rb
including a specific precondition against deleting a provider used in an arena
> Implement precondition checking for deleting

- lib/spaces/models/divisions/resources/resource.rb
- lib/spaces/models/emissions/arenas/emission.rb
- lib/spaces/models/emissions/arenas/providing.rb
- lib/spaces/providers/terraform/providers/aws/artifacts/stanzas/container_task_definition.rb
- lib/spaces/providers/terraform/providers/aws/artifacts/stanzas/resource.rb
> FIX BUG: compute reposistory path does not include the arena identifier

- lib/spaces/providers/terraform/artifacts/artifact.rb
> prettify hcl artifacts

- lib/spaces/providers/terraform/providers/aws/artifacts/artifacts/stanza.rb
- lib/spaces/providers/terraform/providers/aws/artifacts/stanzas/container_registry.rb
- lib/spaces/providers/terraform/providers/aws/artifacts/stanzas/resource.rb
> FIX BUG: qualified resource identifiers not being restricted to maximum length

- lib/spaces/framework/asserting/errors.rb
- lib/spaces/providers/terraform/providers/aws/artifacts/stanzas/container_service.rb
- lib/spaces/providers/terraform/providers/aws/artifacts/stanzas/container_task_definition.rb
- lib/spaces/providers/terraform/providers/aws/artifacts/stanzas/dns_record.rb
- lib/spaces/providers/terraform/providers/aws/artifacts/stanzas/iam_role_policy_attachment.rb
- lib/spaces/providers/terraform/providers/aws/artifacts/stanzas/resource.rb
- lib/spaces/providers/terraform/providers/aws/artifacts/stanzas/route_table_association.rb
- lib/spaces/providers/terraform/providers/aws/artifacts/stanzas/subnet.rb
- x/common/provider_classifier.rb
- x/demo/packer-terraform-aws/applications.rb
- x/demo/packer-terraform-aws/mxr.rb
- x/demo/packer-terraform-aws/registry.rb
- x/managed_functions/applications.rb
- x/managed_functions/mxr.rb
- x/managed_functions/opta_only.rb
- x/managed_functions/registry.rb
included a new test script setting up for only 1 of the managed functions apps
> Refining AWS terraform declarations 

- lib/spaces/framework/lib/hash.rb
- lib/spaces/models/divisions/resources/resource.rb
- lib/spaces/models/divisions/resources/resources.rb
- lib/spaces/models/transforming/divisions/resolvable.rb
- lib/spaces/models/transforming/targeting/flattening.rb
- lib/spaces/models/transforming/targeting/resolving.rb
- lib/spaces/providers/terraform/providers/aws/artifacts/stanzas/container_service.rb
- lib/spaces/providers/terraform/providers/aws/artifacts/stanzas/route_table_association.rb
- lib/spaces/providers/terraform/providers/aws/artifacts/stanzas/subnet.rb
and some twiddles for AWS resource blueprints
> improved configuration merging for resource divisions

- x/managed_functions/applications.rb
- x/managed_functions/mxr.rb
> FIX: build_from commands in mf test scripts
