engines/Spaces

ruby/users/space.rb
This reverts commit 773c1bd1786ea6f589885cd24f6282f910eaba79.
=> Revert "use timestamps as user identifiers"

ruby/docker/files/file.rb, ruby/frameworks/framework.rb, ruby/frameworks/scripts/finalisation.rb, ruby/images/product.rb, ruby/images/space.rb, ruby/images/steps/chown_app_dir.rb, ruby/images/steps/injections.rb, ruby/installations/division.rb, ruby/installations/product.rb, ruby/installations/subdivision.rb, ruby/packages/scripts/installation.rb, ruby/packages/scripts/preparation.rb, ruby/texts/file_text.rb, ruby/texts/script.rb, ruby/users/steps/setup_user.rb, ruby/web_servers/apache/steps/configure.rb
=> FIX BUG:  blueprint keyword “path” name-clashes with #path derivation for scripts

ruby/projects/blueprint.rb
causes NoMethodError (undefined method `[]' for nil:NilClass)
=> FIX BUG: clobbered descriptor in blueprint initialize

ruby/docker/images/space.rb, ruby/spaces/model.rb, ruby/spaces/space.rb
requires blowing away UniversalSpace and re-importing of blueprints
=> strip module names from file names

src/engines/emitting/emissions/descriptive_subdivision.rb
Allows binding to find its targeted blueprint.
=> Add blueprint method to DescriptiveSubdivision.

src/spaces/models/thing.rb
Custom to_json methods need to accept arguments in order to support nested objects.
=> Spaces::Thing :to_json method accepts arguments

api/arenas.rb, api/crud.rb, api/provisioning.rb, api/resolutions.rb, test.rb, tests/provisioning.rb
Use named args for show provisioning for an arena.
Don't test tenants or domains for the time being.
Create provisions by passing in resolution and arena.
=> Index provisioning by areana or resolution. Don't test domains or tenants.

src/engines/blueprinting/divisions/images/images.rb, src/engines/transforming/divisions/divisible.rb
wrong element type OpenStruct at 0 (expected array)
=> FIX BUG: inflating bindings crashes with TypeError

src/engines/resolving/resolution.rb
NoMethodError (undefined method `struct' for nil:NilClass)
=> FIX BUG: when initialising a resolution from a struct, it’s arena is lost

lib/spaces/engines/transforming/emissions/hashing.rb
=> ensure spurious blueprint divisions don’t pollute resolutions

lib/spaces/engines/arenas/space.rb
would also crash for packs and provisioning
=> FIX BUG: deleting arena crashes when there are no resolutions for it yet

lib/spaces/commands/arenas/configuring.rb, lib/spaces/engines/arenas/composition.rb, lib/spaces/engines/transforming/divisions/divisible.rb, lib/spaces/engines/transforming/divisions/division.rb, lib/spaces/engines/transforming/emissions/emission.rb, lib/spaces/engines/transforming/emissions/merging.rb, lib/spaces/providers/virtualisation/lxd/lxd.rb, lib/spaces/universe.rb, x/scripts.rb
There's now a configuration space to hold 'template' arenas which are intended to hold a configuration division which can be merged into any operational arena.
=> Arena merging for configurations

lib/spaces/spaces/lib/ostruct.rb
e.g "\"#<OpenStruct descriptor=#<OpenStruct identifier=\\\"phpmyadmin\\\">, blueprint={:exist=>true}>\""
=> FIX BUG: OpenStruct#to_json returns rubbish result

lib/spaces/engines/transforming/divisions/bindings/binding.rb
broken when changing retuirn type of Divisible#transformed_to in 3d1471d7be119ee9ec5f0664a4f6b58a521258af
=> FIX REGRESSION: NoMethodError (undefined method `runtime' Binding)

lib/spaces/engines/arenas/installing.rb, lib/spaces/engines/arenas/settling.rb
singularized should be singularize
space_for should be space_named
=> FIX BUGS: Arenas::Settling#unsaved crashing with mis-named method calls

lib/spaces/engines/locating/space.rb
should be location.yaml not descriptor.yaml
=> FIX BUG: importing bindings crashes because the wrong file name is written

lib/spaces/models/emissions/commissioning/service.rb, lib/spaces/providers/docker/interfaces/service_interface.rb
=> FIX: container exec call passes bad ENV params

lib/spaces/framework/lib/abbreviating.rb, lib/spaces/framework/lib/string.rb, lib/spaces/providers/terraform/providers/aws/artifacts/stanzas/container_registry.rb, lib/spaces/providers/terraform/providers/aws/artifacts/stanzas/container_service.rb, lib/spaces/providers/terraform/providers/aws/artifacts/stanzas/container_task_definition.rb, lib/spaces/providers/terraform/providers/aws/artifacts/stanzas/resource.rb
if necessary
(they can’t be longer than 32 characters)
=> abbreviate terraform resource identifiers

lib/spaces/framework/asserting/errors.rb
initialize(args) should be initialize(**args), because ruby 3 is dumber about keyword arguments
=> FIX BUG: ERROR - Streaming::OutputStream:  wrong number of arguments

lib/spaces/models/adapters/repositories/repositories.rb, lib/spaces/models/adapters/repositories/repository.rb
when trying to instantiate a repository adapter
=> FIX BUG: `dynamic_type': wrong number of arguments

lib/spaces/commands/packing/building.rb, lib/spaces/models/adapters/repositories/repositories.rb, lib/spaces/models/transforming/adapters/division.rb, lib/spaces/providers/aws/artifacts/stanzas/acm_certificate.rb, lib/spaces/providers/aws/artifacts/stanzas/stanzas.rb, lib/spaces/providers/terraform/providers/aws/artifacts/formats/acm_certificate.rb
│ Error: Attribute redefined
│
│ On startup-service-cluster.resources.tf line 60: The argument "domain_name" │ was already set at startup-service-cluster.resources.tf:53,3-14. Each │ argument may be set only once.
=> FIX BUG: “more” attributes duplicated in HCL
